=== ntls-io/trusted-compute-MVP/drt-examples/sample-data/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Clinical measurements",
  "type": "object",
  "properties": {
    "systolic_bp": { "type": "array", "items": { "type": "number" } },
    "diastolic_bp": { "type": "array", "items": { "type": "number" } },
    "resting_hr": { "type": "array", "items": { "type": "number" } },
    "bmi": { "type": "array", "items": { "type": "number" } }
  },
  "required": ["systolic_bp", "diastolic_bp", "resting_hr", "bmi"]
}

=== ntls-io/trusted-compute-MVP/drt-examples/sample-data/contribution.json
{
  "systolic_bp": [
    135.9,
    149.5,
    127.7,
    137.0,
    139.7,
    133.0,
    113.7,
    130.1,
    131.5,
    121.6,
    125.0,
    122.7
  ],
  "diastolic_bp": [
    85.4,
    89.7,
    73.7,
    86.6,
    75.3,
    92.5,
    86.6,
    79.1,
    84.3,
    85.3,
    81.5,
    86.4
  ],
  "resting_hr": [
    77.1,
    62.9,
    65.5,
    63.1,
    75.5,
    60.3,
    57.5,
    87.8,
    72.7,
    81.9,
    55.4,
    94.2
  ],
  "bmi": [
    33.17,
    22.56,
    33.78,
    23.73,
    25.42,
    27.5,
    29.89,
    27.73,
    23.65,
    28.73,
    24.42,
    31.87
  ]
}
